function(dreamscapes_add_app_icons target)
    set(icons "${CMAKE_CURRENT_SOURCE_DIR}/resources/Appicon/generated")
    if(NOT EXISTS "${icons}/manifest.json")
        message(FATAL_ERROR "Dreamscapes icons are missing. Run tools/generate_app_icons.py with Pillow.")
    endif()
    if(APPLE AND NOT IOS)
        set(runtime_icon "${icons}/macos/Dreamscapes.png")
    else()
        set(runtime_icon "${icons}/common/Dreamscapes.png")
    endif()
    set_source_files_properties("${runtime_icon}" PROPERTIES QT_RESOURCE_ALIAS "Dreamscapes.png")
    qt_add_resources(${target} dreamscapes_branding PREFIX "/branding" FILES "${runtime_icon}")

    if(IOS)
        set(catalog "${icons}/ios/Assets.xcassets")
        target_sources(${target} PRIVATE "${catalog}")
        set_source_files_properties("${catalog}" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
        set_target_properties(${target} PROPERTIES
            XCODE_ATTRIBUTE_ASSETCATALOG_COMPILER_APPICON_NAME AppIcon)
    elseif(APPLE)
        set(icon "${icons}/macos/Dreamscapes.icns")
        target_sources(${target} PRIVATE "${icon}")
        set_source_files_properties("${icon}" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
        set_target_properties(${target} PROPERTIES MACOSX_BUNDLE_ICON_FILE Dreamscapes.icns)
    elseif(ANDROID)
        get_target_property(package_source ${target} QT_ANDROID_PACKAGE_SOURCE_DIR)
        if(NOT package_source OR NOT EXISTS "${package_source}/AndroidManifest.xml")
            message(FATAL_ERROR "Configure Dreamscapes's Android package before its icons")
        endif()
        # Keep authored Java/manifest files intact and stage icons with the package.
        file(GLOB_RECURSE package_inputs CONFIGURE_DEPENDS "${package_source}/*")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${icons}/manifest.json" ${package_inputs})
        set(package "${CMAKE_CURRENT_BINARY_DIR}/app-icons/android")
        file(COPY "${package_source}/" DESTINATION "${package}")
        file(COPY "${icons}/android/res/" DESTINATION "${package}/res")
        set_property(TARGET ${target} PROPERTY QT_ANDROID_PACKAGE_SOURCE_DIR "${package}")
    elseif(WIN32)
        enable_language(RC)
        set(DREAMSCAPES_WINDOWS_ICON "${icons}/windows/Dreamscapes.ico")
        configure_file("${CMAKE_CURRENT_SOURCE_DIR}/platform/windows/Dreamscapes.rc.in"
            "${CMAKE_CURRENT_BINARY_DIR}/Dreamscapes-icon.rc" @ONLY)
        target_sources(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/Dreamscapes-icon.rc")
        set_property(SOURCE "${CMAKE_CURRENT_BINARY_DIR}/Dreamscapes-icon.rc" APPEND PROPERTY OBJECT_DEPENDS "${DREAMSCAPES_WINDOWS_ICON}")
    elseif(EMSCRIPTEN)
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND "${CMAKE_COMMAND}" "-DDREAMSCAPES_WEB_OUTPUT=$<TARGET_FILE_DIR:${target}>"
                "-DDREAMSCAPES_WEB_ICONS=${icons}/web" -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/WebIcons.cmake"
            VERBATIM)
    elseif(UNIX)
        include(GNUInstallDirs)
        install(DIRECTORY "${icons}/linux/hicolor/" DESTINATION "${CMAKE_INSTALL_DATADIR}/icons/hicolor")
        install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/platform/linux/com.iisacc.dreamscapes.desktop"
            DESTINATION "${CMAKE_INSTALL_DATADIR}/applications")
        install(TARGETS ${target} RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
    endif()
endfunction()
