if(NOT EXISTS "${DREAMSCAPES_WEB_OUTPUT}/Dreamscapes.html")
    message(FATAL_ERROR "Qt's generated Dreamscapes.html is required for web icon integration")
endif()
file(COPY "${DREAMSCAPES_WEB_ICONS}/" DESTINATION "${DREAMSCAPES_WEB_OUTPUT}")
file(READ "${DREAMSCAPES_WEB_OUTPUT}/Dreamscapes.html" page)
if(NOT page MATCHES "<!-- Dreamscapes app icons -->")
    string(REPLACE "</head>" "<!-- Dreamscapes app icons -->\n<link rel=\"icon\" href=\"favicon.ico\">\n<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n<link rel=\"manifest\" href=\"manifest.webmanifest\">\n<meta name=\"theme-color\" content=\"#141027\">\n</head>" page "${page}")
    file(WRITE "${DREAMSCAPES_WEB_OUTPUT}/Dreamscapes.html" "${page}")
endif()
